"use client";

import { useEffect, useState } from "react";
import { Check, Coins, Flame, Lock, Palette, Save, ShoppingBag, Sparkles, Trophy, UserRound, Zap } from "lucide-react";
import { CharacterAvatar, PremiumAssetPreview } from "@/components/student/character-avatar";
import { StudentShell } from "@/components/student/student-shell";
import { getStudentLevel } from "@/lib/gamification/calculate-level";
import { avatarShopAssets, type AvatarAsset } from "@/lib/student/avatar-shop";
import { useStudentGame } from "@/lib/gamification/student-game";
import { useStudentProfile, type AvatarConfig, type StudentProfileData } from "@/lib/student/student-profile";

export function ProfilePage() {
  const { profile, save } = useStudentProfile();
  const { state, redeemAvatarAsset } = useStudentGame();
  const [form, setForm] = useState(profile);
  const [saved, setSaved] = useState(false);
  const [activeTab, setActiveTab] = useState<"avatar" | "about">("avatar");
  const [studioTab, setStudioTab] = useState<"body" | "head" | "hair" | "face" | "shirt" | "bottoms" | "shoes">("body");
  const [shopCategory, setShopCategory] = useState<AvatarAsset["category"]>("shirt");
  const level = getStudentLevel(state.xp);
  useEffect(() => setForm(profile), [profile]);

  const update = <K extends keyof StudentProfileData>(field: K, value: StudentProfileData[K]) => { setForm((current) => ({ ...current, [field]: value })); setSaved(false); };
  const updateAvatar = <K extends keyof AvatarConfig>(field: K, value: AvatarConfig[K]) => { setForm((current) => ({ ...current, avatarUrl: null, avatar: { ...current.avatar, [field]: value } })); setSaved(false); };
  function submit(event: React.FormEvent) { event.preventDefault(); save(form); setSaved(true); }
  function equip(asset: AvatarAsset) { setForm((current) => { const next = { ...current, avatarUrl: null, avatar: { ...current.avatar, pantsStyle: asset.category === "bottoms" ? "shorts" as const : current.avatar.pantsStyle, equippedPremium: { ...current.avatar.equippedPremium, [asset.category]: asset.id } } }; save(next); return next; }); setSaved(true); }
  function redeem(asset: AvatarAsset) { const result = redeemAvatarAsset(asset.id, asset.cost); if (result.redeemed) equip(asset); }

  return <StudentShell activeItem="profile"><main className="mx-auto grid w-full max-w-7xl gap-6">
    <header className="relative overflow-hidden rounded-[2rem] bg-gradient-to-br from-blue-800 via-violet-700 to-fuchsia-700 p-6 text-white shadow-[0_24px_70px_rgba(76,29,149,.22)] sm:p-8"><div className="absolute -right-20 -top-24 size-72 rounded-full bg-cyan-300/20 blur-3xl" /><div className="relative flex flex-col gap-6 sm:flex-row sm:items-center"><Avatar profile={form} size="large" /><div className="min-w-0 flex-1"><p className="text-sm font-black uppercase tracking-wider text-violet-200">My avatar</p><h1 className="mt-1 truncate text-4xl font-black sm:text-5xl">{form.displayName}</h1><p className="mt-2 text-lg text-violet-100">{form.grade} · {level.title}</p><div className="mt-4 flex flex-wrap gap-2"><Pill icon={Trophy} text={`Level ${level.level}`} /><Pill icon={Zap} text={`${state.xp} XP`} /><Pill icon={Flame} text={`${state.streak} day streak`} /></div></div><button className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-white px-4 font-black text-violet-800 shadow-sm" onClick={() => setActiveTab("avatar")} type="button"><Palette className="size-5" />Customise</button></div></header>

    <nav aria-label="Profile sections" className="grid grid-cols-2 gap-2 rounded-2xl border border-slate-200 bg-white p-2 shadow-sm"><button aria-current={activeTab === "avatar" ? "page" : undefined} className={`inline-flex min-h-12 items-center justify-center gap-2 rounded-xl font-black ${activeTab === "avatar" ? "bg-violet-700 text-white shadow-md" : "text-slate-600 hover:bg-slate-100"}`} onClick={() => setActiveTab("avatar")} type="button"><Palette className="size-5" />Avatar Studio</button><button aria-current={activeTab === "about" ? "page" : undefined} className={`inline-flex min-h-12 items-center justify-center gap-2 rounded-xl font-black ${activeTab === "about" ? "bg-violet-700 text-white shadow-md" : "text-slate-600 hover:bg-slate-100"}`} onClick={() => setActiveTab("about")} type="button"><UserRound className="size-5" />About Me</button></nav>
    <form className="grid gap-6" onSubmit={submit}>
        {activeTab === "avatar" ? <>
        <section className="rounded-[2rem] border border-violet-200 bg-white p-5 shadow-[var(--shadow-card)] sm:p-6" id="avatar-studio">
          <SectionTitle icon={Palette} title="Avatar studio" description="Build a character that looks and feels like you." />
          <nav aria-label="Avatar customisation categories" className="mt-5 flex gap-2 overflow-x-auto rounded-2xl bg-slate-100 p-2">
            {([["body","Body"],["head","Head"],["hair","Hair"],["face","Face"],["shirt","Shirt"],["bottoms","Pants"],["shoes","Shoes"]] as const).map(([id, label]) => <button aria-current={studioTab === id ? "page" : undefined} className={`min-h-11 shrink-0 rounded-xl px-4 text-sm font-black transition ${studioTab === id ? "bg-violet-700 text-white shadow-md" : "bg-white text-slate-600 hover:text-violet-700"}`} key={id} onClick={() => setStudioTab(id)} type="button">{label}</button>)}
          </nav>
          <div className="mt-6 grid gap-6 xl:grid-cols-[15rem_1fr]">
            <div className="grid place-items-center rounded-3xl bg-gradient-to-br from-cyan-100 to-violet-100 p-5"><CharacterAvatar avatar={form.avatar} className="h-auto w-full max-w-52 rounded-3xl" label={`${form.displayName}'s custom avatar`} /><p className="mt-3 text-center text-xs font-bold text-violet-800">Live preview</p></div>
            <div className="min-h-44 rounded-3xl border border-slate-200 bg-slate-50 p-5">
              {studioTab === "body" ? <div className="grid gap-5"><ChoiceGroup label="Body style" options={[["slim","Slim"],["classic","Classic"],["strong","Strong"]]} value={form.avatar.bodyStyle} onChange={(value) => updateAvatar("bodyStyle", value as AvatarConfig["bodyStyle"])} /><ColorGroup label="Skin colour" colors={["#F6D0B1","#E5A77B","#C68642","#A66A3F","#8D5524","#6B3E26","#4A2A1B"]} value={form.avatar.skinColor} onChange={(value) => updateAvatar("skinColor", value)} /></div> : null}
              {studioTab === "head" ? <ChoiceGroup label="Head shape" options={[["block","Block"],["round","Round"],["oval","Oval"],["wide","Wide"]]} value={form.avatar.headStyle} onChange={(value) => updateAvatar("headStyle", value as AvatarConfig["headStyle"])} /> : null}
              {studioTab === "hair" ? <div className="grid gap-5"><ChoiceGroup label="Hair style" options={[["short","Short"],["afro","Afro"],["braids","Braids"],["locs","Locs"],["mohawk","Mohawk"],["bald","Bald"]]} value={form.avatar.hairStyle} onChange={(value) => updateAvatar("hairStyle", value as AvatarConfig["hairStyle"])} /><ColorGroup label="Hair colour" colors={["#21140F","#4A2A1B","#7A4A25","#D4A017","#8B1E3F","#312E81"]} value={form.avatar.hairColor} onChange={(value) => updateAvatar("hairColor", value)} /></div> : null}
              {studioTab === "face" ? <ColorGroup label="Eye colour" colors={["#3B2414","#6B4F2A","#2563EB","#15803D","#64748B","#111827"]} value={form.avatar.eyeColor} onChange={(value) => updateAvatar("eyeColor", value)} /> : null}
              {studioTab === "shirt" ? <div className="grid gap-5"><ChoiceGroup label="Shirt design" options={[["skulkid","SkulKid"],["math","Math Club"],["science","Science Lab"],["reader","Book Club"],["plain","Plain"]]} value={form.avatar.shirtStyle} onChange={(value) => updateAvatar("shirtStyle", value as AvatarConfig["shirtStyle"])} /><ColorGroup label="Shirt colour" colors={["#2563EB","#7C3AED","#16A34A","#DC2626","#F59E0B","#0F172A"]} value={form.avatar.shirtColor} onChange={(value) => updateAvatar("shirtColor", value)} /></div> : null}
              {studioTab === "bottoms" ? <div className="grid gap-5"><ChoiceGroup label="Pants style" options={[["trousers","Trousers"],["shorts","Shorts"],["skirt","Skirt"]]} value={form.avatar.pantsStyle} onChange={(value) => updateAvatar("pantsStyle", value as AvatarConfig["pantsStyle"])} /><ColorGroup label="Pants colour" colors={["#172554","#312E81","#14532D","#3F3F46","#7C2D12","#111827"]} value={form.avatar.pantsColor} onChange={(value) => updateAvatar("pantsColor", value)} /></div> : null}
              {studioTab === "shoes" ? <ColorGroup label="Shoe colour" colors={["#FFFFFF","#111827","#DC2626","#2563EB","#F59E0B"]} value={form.avatar.shoeColor} onChange={(value) => updateAvatar("shoeColor", value)} /> : null}
            </div>
          </div>
        </section>
        <section className="rounded-[2rem] border border-amber-200 bg-white p-5 shadow-[var(--shadow-card)] sm:p-6">
          <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><SectionTitle icon={ShoppingBag} title="Premium avatar shop" description="Choose a category, preview the gear and redeem your favourite." /><div className="inline-flex shrink-0 items-center gap-2 rounded-2xl bg-amber-100 px-4 py-3 font-black text-amber-950"><Coins className="size-5" />{state.avatarPoints} points</div></div>
          <nav aria-label="Premium shop categories" className="mt-5 flex gap-2 overflow-x-auto rounded-2xl bg-amber-50 p-2">
            {([["shirt","Shirts"],["bottoms","Pants"],["shoes","Sneakers"],["cap","Caps"],["glasses","Glasses"],["watch","Watches"],["bag","Bags"],["skateboard","Boards"]] as const).map(([category, label]) => <button aria-current={shopCategory === category ? "page" : undefined} className={`min-h-11 shrink-0 rounded-xl px-4 text-sm font-black transition ${shopCategory === category ? "bg-amber-500 text-slate-950 shadow-md" : "bg-white text-slate-600 hover:text-amber-800"}`} key={category} onClick={() => setShopCategory(category)} type="button">{label}</button>)}
          </nav>
          <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{avatarShopAssets.filter((asset) => asset.category === shopCategory).map((asset) => { const unlocked = state.unlockedAvatarAssetIds.includes(asset.id); const equipped = form.avatar.equippedPremium[asset.category] === asset.id; const affordable = state.avatarPoints >= asset.cost; return <article className={`overflow-hidden rounded-2xl border-2 ${equipped ? "border-emerald-400 bg-emerald-50" : unlocked ? "border-blue-200 bg-blue-50" : "border-slate-200 bg-slate-50"}`} key={asset.id}><div className="relative grid h-48 place-items-center bg-gradient-to-br from-cyan-100 via-white to-violet-100 p-3"><PremiumAssetPreview asset={asset} className="h-40 w-full" /><span className="absolute right-3 top-3 rounded-full bg-white/95 px-2.5 py-1 text-xs font-black capitalize text-slate-700 shadow-sm">{asset.category === "bottoms" ? "pants" : asset.category}</span><span className="absolute bottom-3 left-3 rounded-lg px-2.5 py-1 text-xs font-black text-white shadow-sm" style={{ backgroundColor: asset.colour }}>{asset.brand}</span></div><div className="p-4"><h3 className="font-black">{asset.name}</h3><p className="mt-1 flex items-center gap-1 text-sm font-bold text-amber-800"><Coins className="size-4" />{asset.cost} points</p>{unlocked ? <button className={`mt-4 min-h-10 w-full rounded-xl font-black ${equipped ? "bg-emerald-600 text-white" : "bg-blue-700 text-white"}`} disabled={equipped} onClick={() => equip(asset)} type="button">{equipped ? "Equipped" : "Equip"}</button> : <button className="mt-4 inline-flex min-h-10 w-full items-center justify-center gap-2 rounded-xl bg-slate-950 font-black text-white disabled:cursor-not-allowed disabled:opacity-40" disabled={!affordable} onClick={() => redeem(asset)} type="button"><Lock className="size-4" />{affordable ? "Redeem" : `Need ${asset.cost - state.avatarPoints} more`}</button>}</div></article>; })}</div>
          <p className="mt-4 text-xs leading-5 text-muted">Adidas, Nike, Puma and their marks are trademarks of their respective owners. SkulKid is not affiliated with or endorsed by these brands.</p>
        </section>
        </> : null}
        {activeTab === "about" ? <>
        <section className="rounded-[2rem] border border-slate-200 bg-white p-5 shadow-[var(--shadow-card)] sm:p-6"><SectionTitle icon={UserRound} title="About me" description="The details shown on your student profile." /><div className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="Display name"><input required value={form.displayName} onChange={(event) => update("displayName", event.target.value)} /></Field><Field label="Age"><input max={18} min={5} required type="number" value={form.age} onChange={(event) => update("age", Number(event.target.value))} /></Field><Field label="Grade"><select value={form.grade} onChange={(event) => update("grade", event.target.value)}>{[1,2,3,4,5,6].map((grade) => <option key={grade}>Basic {grade}</option>)}</select></Field><Field label="School"><input placeholder="Enter your school" value={form.school} onChange={(event) => update("school", event.target.value)} /></Field><Field className="sm:col-span-2" label="My learning bio"><textarea maxLength={180} rows={3} value={form.bio} onChange={(event) => update("bio", event.target.value)} /><span className="mt-1 block text-right text-xs text-muted">{form.bio.length}/180</span></Field></div></section>

        <section className="rounded-[2rem] border border-slate-200 bg-white p-5 shadow-[var(--shadow-card)] sm:p-6"><SectionTitle icon={Sparkles} title="Learning preferences" description="Personalise your learning targets and favourite subject." /><div className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="Favourite subject"><select value={form.favouriteSubject} onChange={(event) => update("favouriteSubject", event.target.value as StudentProfileData["favouriteSubject"])}><option>Mathematics</option><option>English</option><option>Science</option></select></Field><Field label="Daily XP goal"><select value={form.dailyGoalXp} onChange={(event) => update("dailyGoalXp", Number(event.target.value))}><option value={30}>30 XP · Light</option><option value={60}>60 XP · Regular</option><option value={100}>100 XP · Champion</option></select></Field></div></section>

        </> : null}
        <button className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-primary px-6 font-black text-white shadow-sm hover:bg-primary-dark" type="submit">{saved ? <Check className="size-5" /> : <Save className="size-5" />}{saved ? "Changes saved" : "Save changes"}</button>
    </form>
  </main></StudentShell>;
}

function Avatar({ profile, size = "small" }: { profile: StudentProfileData; size?: "small" | "large" }) { return <div className="shrink-0 overflow-hidden rounded-full border-4 border-white/80 shadow-xl"><CharacterAvatar avatar={profile.avatar} className={size === "large" ? "size-24 sm:size-28" : "size-11"} label={`${profile.displayName}'s avatar`} /></div>; }
function ChoiceGroup({ label, options, value, onChange }: { label: string; options: string[][]; value: string; onChange: (value: string) => void }) { return <fieldset><legend className="text-sm font-black text-slate-800">{label}</legend><div className="mt-2 flex flex-wrap gap-2">{options.map(([option, name]) => <button aria-pressed={value === option} className={`min-h-10 rounded-xl border-2 px-3 text-sm font-bold ${value === option ? "border-violet-600 bg-violet-50 text-violet-900" : "border-slate-200 bg-white text-slate-700"}`} key={option} onClick={() => onChange(option)} type="button">{name}</button>)}</div></fieldset>; }
function ColorGroup({ label, colors, value, onChange }: { label: string; colors: string[]; value: string; onChange: (value: string) => void }) { return <fieldset><legend className="text-sm font-black text-slate-800">{label}</legend><div className="mt-2 flex flex-wrap gap-2">{colors.map((color) => <button aria-label={`${label} ${color}`} aria-pressed={value === color} className={`size-10 rounded-full border-4 shadow-sm ${value === color ? "border-violet-600 ring-2 ring-violet-200" : "border-white"}`} key={color} onClick={() => onChange(color)} style={{ backgroundColor: color }} type="button" />)}</div></fieldset>; }
function Field({ label, className = "", children }: { label: string; className?: string; children: React.ReactNode }) { return <label className={`block text-sm font-black text-text-secondary [&_input]:mt-2 [&_input]:min-h-12 [&_input]:w-full [&_input]:rounded-xl [&_input]:border [&_input]:border-slate-300 [&_input]:px-4 [&_select]:mt-2 [&_select]:min-h-12 [&_select]:w-full [&_select]:rounded-xl [&_select]:border [&_select]:border-slate-300 [&_select]:bg-white [&_select]:px-4 [&_textarea]:mt-2 [&_textarea]:w-full [&_textarea]:rounded-xl [&_textarea]:border [&_textarea]:border-slate-300 [&_textarea]:p-4 ${className}`}>{label}{children}</label>; }
function SectionTitle({ icon: Icon, title, description }: { icon: React.ElementType; title: string; description: string }) { return <div className="flex items-start gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-2xl bg-blue-100 text-blue-700"><Icon className="size-5" /></span><div><h2 className="text-xl font-black">{title}</h2><p className="mt-1 text-sm text-text-secondary">{description}</p></div></div>; }
function Pill({ icon: Icon, text }: { icon: React.ElementType; text: string }) { return <span className="inline-flex items-center gap-1.5 rounded-full bg-white/10 px-3 py-1.5 text-sm font-black ring-1 ring-white/20"><Icon className="size-4 text-amber-300" />{text}</span>; }
