"use client";
import { useEffect,useState } from "react";
import Image from "next/image";
import { BarChart3,Clock3,ShieldCheck,Video } from "lucide-react";
type Data={classes:Array<{id:string;name:string}>;schedules:Array<{id:string;classId:string;dayOfWeek:number;startsAt:string;endsAt:string}>;videos:Array<{id:string;title:string;channelTitle:string;thumbnailUrl:string|null;severity:string;summary:string;categories:string[]}>;analytics:{searches:number;watchMinutes:number;completions:number;reports:number}};
const days=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];
export default function Page(){const[data,setData]=useState<Data|null>(null),[error,setError]=useState("");const load=async()=>{const r=await fetch("/api/teacher/break-zone");const b=await r.json();if(!r.ok)throw new Error(b.error);setData(b)};useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 async function addWindow(classId:string){const day=Number(prompt("Day: 0 Sunday, 1 Monday … 6 Saturday","1"));const startsAt=prompt("Start time (24-hour HH:MM)","10:00");const endsAt=prompt("End time (24-hour HH:MM)","10:30");if(!startsAt||!endsAt||day<0||day>6)return;const existing=(data?.schedules??[]).filter(x=>x.classId===classId).map(x=>({dayOfWeek:x.dayOfWeek,startsAt:x.startsAt.slice(0,5),endsAt:x.endsAt.slice(0,5),enabled:true}));const r=await fetch("/api/teacher/break-zone",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action:"schedule",classId,windows:[...existing,{dayOfWeek:day,startsAt,endsAt,enabled:true}]})});const b=await r.json();if(!r.ok)setError(b.error);else load();}
 async function decide(videoId:string,decision:"approved"|"rejected"){const classId=prompt(`Class ID to ${decision}. Copy one from the schedule cards below.`);const reason=prompt("Give a safeguarding reason (required).");if(!classId||!reason)return;const r=await fetch("/api/teacher/break-zone",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action:"decision",videoId,classIds:[classId],decision,reason})});const b=await r.json();if(!r.ok)setError(b.error);else{if(b.severeAlert)alert("This severe override was immediately alerted to administrators.");load()}}
 return <main className="mx-auto max-w-7xl space-y-7"><header><span className="inline-flex items-center gap-2 text-sm font-black text-violet-700"><ShieldCheck className="size-4"/>Supervised video controls</span><h1 className="mt-2 text-3xl font-black">Break Zone</h1><p className="mt-1 text-slate-600">Set break hours, review requested videos and see how your classes use the space.</p></header>{error?<p className="rounded-xl bg-red-50 p-3 font-bold text-red-800">{error}</p>:null}
 <section className="grid gap-3 sm:grid-cols-4">{Object.entries(data?.analytics??{}).map(([k,v])=><div className="rounded-2xl border bg-white p-4" key={k}><BarChart3 className="size-5 text-violet-600"/><p className="mt-3 text-2xl font-black">{v}</p><p className="text-xs font-black uppercase text-slate-500">{k.replace(/([A-Z])/g," $1")}</p></div>)}</section>
 <section><h2 className="text-xl font-black">Class break schedules</h2><div className="mt-3 grid gap-3 lg:grid-cols-2">{data?.classes.map(c=><div className="rounded-2xl border bg-white p-4" key={c.id}><div className="flex justify-between gap-3"><div><p className="font-black">{c.name}</p><code className="text-[10px] text-slate-400">{c.id}</code></div><button className="rounded-xl bg-slate-950 px-3 py-2 text-xs font-black text-white" onClick={()=>addWindow(c.id)}>Add window</button></div><div className="mt-3 flex flex-wrap gap-2">{data.schedules.filter(x=>x.classId===c.id).map(x=><span className="rounded-full bg-violet-50 px-3 py-1 text-xs font-bold text-violet-800" key={x.id}><Clock3 className="mr-1 inline size-3"/>{days[x.dayOfWeek]} {x.startsAt.slice(0,5)}–{x.endsAt.slice(0,5)}</span>)}{!data.schedules.some(x=>x.classId===c.id)?<span className="text-xs font-bold text-amber-700">No window — playback is blocked.</span>:null}</div></div>)}</div></section>
 <section><h2 className="text-xl font-black">Videos needing attention</h2><div className="mt-3 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data?.videos.map(v=><article className="overflow-hidden rounded-2xl border bg-white" key={v.id}>{v.thumbnailUrl?<div className="relative aspect-video"><Image alt="" fill className="object-cover" src={v.thumbnailUrl}/></div>:null}<div className="p-4"><p className="text-xs font-black uppercase text-amber-700">{v.severity} · {v.categories.join(", ")||"awaiting analysis"}</p><h3 className="mt-1 font-black">{v.title}</h3><p className="text-sm text-slate-500">{v.channelTitle}</p><p className="mt-2 line-clamp-3 text-xs text-slate-600">{v.summary}</p><div className="mt-4 flex gap-2"><button className="flex-1 rounded-xl bg-emerald-600 p-2 text-xs font-black text-white" onClick={()=>decide(v.id,"approved")}>Approve for class</button><button className="rounded-xl bg-red-50 px-3 text-xs font-black text-red-700" onClick={()=>decide(v.id,"rejected")}>Reject</button></div></div></article>)}</div></section></main>}
