"use client";
import Image from "next/image";
import { useEffect,useState } from "react";
import { AlertTriangle,CheckCircle2,Clock3,RefreshCw,ShieldAlert } from "lucide-react";
type Data={videos:Array<{id:string;title:string;channelTitle:string;thumbnailUrl:string|null;moderationStatus:string;severity:string;categories:string[];summary:string;updatedAt:string}>;reports:Array<{id:string;reason:string;status:string;createdAt:string}>;alerts:Array<{id:string;action:string;createdAt:string}>;readiness:Record<string,boolean>;stats:Record<string,number>;config:{enabled:boolean;dailyXpCap:number;completionXp:number;retentionDays:number;moderationModel:string}};
export default function Page(){const[data,setData]=useState<Data|null>(null),[error,setError]=useState("");const load=async()=>{const r=await fetch("/api/admin/break-zone");const b=await r.json();if(!r.ok)throw new Error(b.error);setData(b)};useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 async function decide(videoId:string,decision:string){const reason=prompt(`Reason for ${decision} (required):`);if(!reason)return;const r=await fetch("/api/admin/break-zone",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({videoId,decision,reason})});const b=await r.json();if(!r.ok)setError(b.error);else load();}
 async function configure(){if(!data)return;const dailyXpCap=Number(prompt("Daily Break Zone XP cap",String(data.config.dailyXpCap)));const completionXp=Number(prompt("XP per meaningful completion",String(data.config.completionXp)));const retentionDays=Number(prompt("Identifiable history retention days",String(data.config.retentionDays)));const moderationModel=prompt("Gemini moderation model",data.config.moderationModel);if(!moderationModel)return;const r=await fetch("/api/admin/break-zone",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({enabled:data.config.enabled,dailyXpCap,completionXp,retentionDays,moderationModel})});const b=await r.json();if(!r.ok)setError(b.error);else load();}
 return <main className="mx-auto max-w-7xl space-y-7"><header><p className="text-sm font-black text-emerald-700">CHILD-SAFETY OPERATIONS</p><h1 className="mt-1 text-3xl font-black">Break Zone moderation</h1><p className="mt-1 text-slate-600">Global catalogue, queue health, reports and fully audited decisions.</p></header>{error?<p className="rounded-xl bg-red-50 p-3 font-bold text-red-800">{error}</p>:null}
 <section className="grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{Object.entries(data?.stats??{}).map(([k,v])=><div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm" key={k}><p className="text-2xl font-black">{v}</p><p className="mt-1 text-[10px] font-black uppercase text-slate-500">{k}</p></div>)}</section>
 <section className="rounded-2xl border bg-white p-5"><div className="flex items-center justify-between gap-3"><h2 className="font-black">Production readiness</h2><button className="rounded-xl bg-slate-950 px-3 py-2 text-xs font-black text-white" onClick={configure}>Configure policy</button></div><div className="mt-3 flex flex-wrap gap-3">{Object.entries(data?.readiness??{}).map(([k,v])=><span className={`inline-flex items-center gap-2 rounded-full px-3 py-2 text-xs font-black ${v?"bg-emerald-50 text-emerald-800":"bg-red-50 text-red-800"}`} key={k}>{v?<CheckCircle2 className="size-4"/>:<AlertTriangle className="size-4"/>}{k}: {v?"ready":"missing"}</span>)}</div>{data?.config?<p className="mt-3 text-xs font-bold text-slate-500">XP {data.config.completionXp}/video · cap {data.config.dailyXpCap}/day · retention {data.config.retentionDays} days · {data.config.moderationModel}</p>:null}</section>
 {(data?.alerts.length||data?.reports.length)?<section className="rounded-2xl border border-red-200 bg-red-50 p-5"><h2 className="flex items-center gap-2 font-black text-red-900"><ShieldAlert/>Open safety signals</h2><p className="mt-2 text-sm font-semibold text-red-800">{data.alerts.length} severe overrides or suspensions · {data.reports.filter(x=>x.status==="open").length} open student reports</p></section>:null}
 <section><h2 className="text-xl font-black">Video catalogue and queue</h2><div className="mt-3 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data?.videos.map(v=><article className="overflow-hidden rounded-2xl border bg-white shadow-sm" key={v.id}>{v.thumbnailUrl?<div className="relative aspect-video"><Image alt="" className="object-cover" fill src={v.thumbnailUrl}/></div>:null}<div className="p-4"><div className="flex items-center justify-between gap-2"><span className={`rounded-full px-2 py-1 text-[10px] font-black uppercase ${v.moderationStatus==="approved"?"bg-emerald-100 text-emerald-800":v.moderationStatus==="suspended"?"bg-red-100 text-red-800":"bg-amber-100 text-amber-800"}`}>{v.moderationStatus}</span><span className="text-[10px] font-bold text-slate-400">{new Date(v.updatedAt).toLocaleString()}</span></div><h3 className="mt-3 font-black">{v.title}</h3><p className="text-xs font-semibold text-slate-500">{v.channelTitle}</p><p className="mt-2 text-xs font-bold text-red-700">{v.severity} {v.categories.join(", ")}</p><p className="mt-2 line-clamp-3 text-xs text-slate-600">{v.summary}</p><div className="mt-4 grid grid-cols-2 gap-2"><button className="rounded-xl bg-emerald-600 p-2 text-xs font-black text-white" onClick={()=>decide(v.id,"approved")}>Approve</button><button className="rounded-xl bg-red-600 p-2 text-xs font-black text-white" onClick={()=>decide(v.id,"suspended")}>Suspend</button><button className="rounded-xl bg-slate-100 p-2 text-xs font-black" onClick={()=>decide(v.id,"rejected")}>Reject</button><button className="inline-flex items-center justify-center gap-1 rounded-xl bg-violet-100 p-2 text-xs font-black text-violet-800" onClick={()=>decide(v.id,"reanalyze")}><RefreshCw className="size-3"/>Recheck</button></div></div></article>)}</div></section></main>}
