"use client";

import { useEffect, useState } from "react";
import { AlertTriangle, CheckCircle2, CircleDashed, ExternalLink, Plus, Server, ShieldAlert, Wrench, XCircle } from "lucide-react";
import { SkulKidCard } from "@/components/shared/skulkid-card";
import { AdminPageHeader } from "@/components/admin/admin-page-header";

type Operations = {
  checkedAt: string;
  health: Array<{ name: string; status: string; detail: string; latencyMs?: number }>;
  incidents: Array<{ id: string; title: string; summary: string; severity: string; status: string; affectedService: string; createdAt: string }>;
  services: Array<{ id: string; name: string; category: string; provider: string; status: string; consoleUrl?: string; runbookUrl?: string; notes: string }>;
  maintenance: unknown[];
  responsibilities: Array<{ area: string; duty: string; status: "available" | "integration" | "runbook"; destination: string }>;
};

export default function AdminOperationsPage() {
  const [data, setData] = useState<Operations | null>(null);
  const [error, setError] = useState("");
  const [showIncident, setShowIncident] = useState(false);
  const [notice, setNotice] = useState("");
  async function load() { try { const response = await fetch("/api/admin/operations", { cache: "no-store" }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setData(result); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to load operations."); } }
  useEffect(() => { void load(); }, []);
  return <main className="mx-auto grid w-full max-w-[96rem] gap-6">
    <AdminPageHeader actions={<button className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-white px-5 font-black text-slate-950" onClick={() => setShowIncident(true)}><Plus className="size-5" />Declare incident</button>} description="Health, incidents, provider readiness, recovery, maintenance, inventory, and operational responsibility." eyebrow="System administration" icon={Wrench} title="Operations" tone="dark" />
    {error ? <div role="alert" className="rounded-2xl bg-rose-50 p-4 font-bold text-rose-900">{error}</div> : null}
    {notice ? <div role="status" className="rounded-2xl bg-emerald-50 p-4 font-bold text-emerald-900">{notice}</div> : null}
    <section><div className="flex items-end justify-between"><div><p className="text-xs font-black uppercase tracking-wider text-emerald-700">Live diagnostics</p><h2 className="mt-1 text-2xl font-black">Service health</h2></div><p className="text-xs text-slate-500">{data ? `Checked ${new Date(data.checkedAt).toLocaleString()}` : "Checking…"}</p></div><div className="mt-3 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{data?.health.map((item) => <Health item={item} key={item.name} />)}</div></section>
    <section className="grid gap-4 xl:grid-cols-[1.2fr_.8fr]">
      <SkulKidCard className="overflow-hidden"><div className="border-b border-slate-200 p-5"><h2 className="text-xl font-black">Active incidents</h2><p className="mt-1 text-sm text-slate-500">Track diagnosis, impact, and resolution ownership.</p></div><div className="divide-y divide-slate-100">{data?.incidents.length ? data.incidents.map((incident) => <article className="p-5" key={incident.id}><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2 py-1 text-xs font-black uppercase ${incident.severity === "critical" ? "bg-rose-100 text-rose-900" : "bg-amber-100 text-amber-900"}`}>{incident.severity}</span><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-black capitalize">{incident.status}</span></div><h3 className="mt-3 font-black">{incident.title}</h3><p className="mt-1 text-sm text-slate-600">{incident.summary || "No incident summary supplied."}</p><p className="mt-2 text-xs text-slate-500">{incident.affectedService} · {new Date(incident.createdAt).toLocaleString()}</p>{incident.status !== "resolved" ? <button className="mt-3 rounded-xl border border-slate-300 px-3 py-2 text-xs font-black" onClick={async () => { const reason = window.prompt("Resolution note:"); if (!reason) return; const response = await fetch("/api/admin/operations", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ incidentId: incident.id, status: "resolved", reason }) }); const result = await response.json(); if (!response.ok) setError(result.error); else { setNotice("Incident resolved and audited."); await load(); } }}>Resolve incident</button> : null}</article>) : <div className="flex min-h-36 items-center gap-3 p-5 text-emerald-900"><CheckCircle2 className="size-6" /><b>No incidents recorded.</b></div>}</div></SkulKidCard>
      <SkulKidCard className="overflow-hidden"><div className="border-b border-slate-200 p-5"><h2 className="text-xl font-black">Service inventory</h2><p className="mt-1 text-sm text-slate-500">Providers, ownership, licences, and runbooks.</p></div><div className="divide-y divide-slate-100">{data?.services.map((service) => <div className="p-4" key={service.id}><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-slate-100"><Server className="size-4" /></span><div><p className="font-black">{service.name}</p><p className="text-xs text-slate-500">{service.provider || "Provider not configured"} · {service.category}</p></div><Status value={service.status} /></div><p className="mt-2 text-xs leading-5 text-slate-600">{service.notes}</p>{service.consoleUrl || service.runbookUrl ? <a className="mt-2 inline-flex items-center gap-1 text-xs font-bold text-emerald-700" href={service.consoleUrl || service.runbookUrl} rel="noreferrer" target="_blank">Open resource <ExternalLink className="size-3" /></a> : null}</div>)}</div></SkulKidCard>
    </section>
    <SkulKidCard className="overflow-hidden"><div className="border-b border-slate-200 p-5"><p className="text-xs font-black uppercase tracking-wider text-emerald-700">CISA / O*NET coverage</p><h2 className="mt-1 text-xl font-black">System administrator responsibility matrix</h2><p className="mt-1 text-sm text-slate-500">Physical and provider-controlled duties are tracked honestly instead of reporting fabricated success.</p></div><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th className="p-4">Area</th><th className="p-4">Responsibility</th><th className="p-4">Capability</th></tr></thead><tbody className="divide-y divide-slate-100">{data?.responsibilities.map((item) => <tr key={`${item.area}-${item.duty}`}><td className="p-4 font-black">{item.area}</td><td className="p-4 text-slate-600">{item.duty}</td><td className="p-4"><ResponsibilityStatus status={item.status} /></td></tr>)}</tbody></table></div></SkulKidCard>
    <SkulKidCard className="flex flex-col gap-4 border-amber-200 bg-amber-50 p-5 sm:flex-row sm:items-center"><div className="flex-1"><h2 className="font-black text-amber-950">Backup and recovery</h2><p className="mt-1 text-sm text-amber-900">A backup can only be triggered when the server-only provider endpoint is configured. Credentials never reach this page.</p></div><button className="min-h-11 rounded-xl bg-amber-900 px-4 font-black text-white" onClick={async () => { const reason = window.prompt("Reason for running a backup:"); if (!reason) return; const response = await fetch("/api/admin/operations", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "run_backup", reason }) }); const result = await response.json(); if (!response.ok) setError(result.error); else setNotice(result.message); }}>Run backup</button></SkulKidCard>
    {showIncident ? <IncidentDialog onClose={() => setShowIncident(false)} onDone={async () => { setShowIncident(false); await load(); }} /> : null}
  </main>;
}

function Health({ item }: { item: Operations["health"][number] }) { const good = item.status === "operational" || item.status === "configured"; return <SkulKidCard className="p-4"><div className="flex items-center gap-2">{good ? <CheckCircle2 className="size-5 text-emerald-600" /> : item.status === "not_configured" ? <CircleDashed className="size-5 text-slate-400" /> : <XCircle className="size-5 text-rose-600" />}<b className="text-sm">{item.name}</b></div><p className="mt-3 text-xs leading-5 text-slate-500">{item.detail}{item.latencyMs !== undefined ? ` · ${item.latencyMs}ms` : ""}</p></SkulKidCard>; }
function Status({ value }: { value: string }) { return <span className={`ml-auto rounded-full px-2 py-1 text-[10px] font-black uppercase ${value === "operational" ? "bg-emerald-50 text-emerald-800" : value === "not_configured" ? "bg-slate-100 text-slate-600" : "bg-amber-50 text-amber-800"}`}>{value.replaceAll("_", " ")}</span>; }
function ResponsibilityStatus({ status }: { status: "available" | "integration" | "runbook" }) { const value = status === "available" ? "Available" : status === "integration" ? "Provider integration required" : "External / physical runbook"; return <span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-xs font-black ${status === "available" ? "bg-emerald-50 text-emerald-800" : status === "integration" ? "bg-amber-50 text-amber-900" : "bg-slate-100 text-slate-700"}`}>{status === "available" ? <Wrench className="size-3" /> : status === "integration" ? <AlertTriangle className="size-3" /> : <ShieldAlert className="size-3" />}{value}</span>; }
function IncidentDialog({ onClose, onDone }: { onClose: () => void; onDone: () => void }) { const [form, setForm] = useState({ title: "", summary: "", severity: "medium", affectedService: "SkulKid application", reason: "Incident declared after operational review" }); const [error, setError] = useState(""); async function submit(event: React.FormEvent) { event.preventDefault(); const response = await fetch("/api/admin/operations", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const result = await response.json(); if (!response.ok) { setError(result.error); return; } onDone(); } return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-3"><form className="grid w-full max-w-lg gap-4 rounded-2xl bg-white p-6 shadow-2xl" onSubmit={submit}><h2 className="text-2xl font-black">Declare an incident</h2>{[["title","Title"],["affectedService","Affected service"],["summary","Summary"],["reason","Administrative reason"]].map(([key,label]) => <label className="grid gap-2 text-sm font-bold" key={key}>{label}<input className="min-h-11 rounded-xl border border-slate-300 px-3" value={form[key as keyof typeof form]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} /></label>)}<label className="grid gap-2 text-sm font-bold">Severity<select className="min-h-11 rounded-xl border border-slate-300 px-3" value={form.severity} onChange={(event) => setForm({ ...form, severity: event.target.value })}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option></select></label>{error ? <p className="rounded-xl bg-rose-50 p-3 text-sm font-bold text-rose-800">{error}</p> : null}<div className="flex justify-end gap-2"><button type="button" className="rounded-xl border border-slate-300 px-4 py-3 font-bold" onClick={onClose}>Cancel</button><button className="rounded-xl bg-rose-600 px-4 py-3 font-black text-white">Declare incident</button></div></form></div>; }
