"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { Archive, CalendarClock, ClipboardList, Copy, Gift, Loader2, Plus, Search, Send, Sparkles, X } from "lucide-react";
import type { ClassQuizQuestion, TeacherClassSummary } from "@/lib/classes/types";
import { QuizEditorDialog } from "@/components/teacher/quiz-editor-dialog";
import { TeacherGuideLink } from "@/components/teacher/teacher-guide-link";
import { useOnlineStatus } from "@/lib/network/use-online";

export type Quiz = {
  id:string; title:string; description:string; subject:string; gradeLevels:number[]; questions:ClassQuizQuestion[];
  baseXpReward:number; passingScore:number; maxAttempts:number; version:number; status:"draft"|"ready"|"archived";
  assignmentCount:number; attemptCount:number; averageScore:number|null; passRate:number|null;
};
const blankQuestion=():ClassQuizQuestion=>({id:crypto.randomUUID(),prompt:"",type:"multiple_choice",options:["","","",""],correctIndex:0,explanation:""});

export function TeacherQuizLibrary({initialCreate=false}:{initialCreate?:boolean}){
 const [quizzes,setQuizzes]=useState<Quiz[]>([]),[classes,setClasses]=useState<TeacherClassSummary[]>([]);
 const [query,setQuery]=useState(""),[status,setStatus]=useState("active"),[subject,setSubject]=useState("all");
 const [editing,setEditing]=useState<Quiz|null>(null),[assigning,setAssigning]=useState<Quiz|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const createDeepLinkHandled=useRef(false);
 async function load(){setBusy(true);try{const [q,c]=await Promise.all([fetch("/api/teacher/quizzes",{cache:"no-store"}),fetch("/api/teacher/classes",{cache:"no-store"})]);const qd=await q.json(),cd=await c.json();if(!q.ok)throw new Error(qd.error);setQuizzes(qd.quizzes??[]);setClasses(cd.classes??[])}catch(e){setError(e instanceof Error?e.message:"Unable to load quizzes.")}finally{setBusy(false)}}
 useEffect(()=>{void load()},[]);
 useEffect(()=>{if(!initialCreate||createDeepLinkHandled.current)return;createDeepLinkHandled.current=true;setEditing(newQuiz());const url=new URL(window.location.href);url.searchParams.delete("create");window.history.replaceState(window.history.state,"",`${url.pathname}${url.search}${url.hash}`)},[initialCreate]);
 const visible=useMemo(()=>quizzes.filter(q=>`${q.title} ${q.description}`.toLowerCase().includes(query.toLowerCase())&&(status==="all"||(status==="active"?q.status!=="archived":q.status===status))&&(subject==="all"||q.subject===subject)),[quizzes,query,status,subject]);
 async function mutate(body:unknown,method="PATCH"){setBusy(true);setError("");try{const r=await fetch("/api/teacher/quizzes",{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw new Error(d.error);setQuizzes(d.quizzes??[]);setEditing(null);setMessage("Quiz library updated.")}catch(e){setError(e instanceof Error?e.message:"Unable to save quiz.")}finally{setBusy(false)}}
 async function saveQuiz(body:Quiz,method:"POST"|"PATCH"){setBusy(true);setError("");try{const r=await fetch("/api/teacher/quizzes",{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to save quiz.");setQuizzes(d.quizzes??[]);setEditing(null);setMessage(d.moderation?.state&&d.moderation.state!=="published"?d.moderation.message:body.status==="ready"?"Quiz marked ready.":"Quiz draft saved.")}catch(e){const text=e instanceof Error?e.message:"Unable to save quiz.";setError(text);throw new Error(text)}finally{setBusy(false)}}
 return <main className="mx-auto grid w-full max-w-[90rem] gap-6"><header className="relative overflow-hidden rounded-[2rem] bg-gradient-to-br from-slate-950 via-violet-950 to-blue-800 p-6 text-white sm:p-8"><Sparkles className="size-7 text-amber-300"/><h1 className="mt-3 text-3xl font-black sm:text-5xl">Quiz Library</h1><p className="mt-3 max-w-2xl text-violet-100">Create once, then send a frozen quiz challenge to one or many classes.</p><div className="mt-5 flex flex-col gap-3 sm:flex-row"><TeacherGuideLink className="border-white/20 bg-white/10 text-white hover:border-white/40 hover:bg-white/20 hover:text-white" topic="reusable-quiz"/><button className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-white px-5 font-black text-violet-950" onClick={()=>setEditing(newQuiz())}><Plus className="size-5"/>Create reusable quiz</button></div></header>
 {error?<p className="rounded-xl bg-rose-50 p-4 font-bold text-rose-800">{error}</p>:null}{message?<p className="rounded-xl bg-emerald-50 p-4 font-bold text-emerald-800">{message}</p>:null}
 <section className="rounded-[1.5rem] border bg-white p-4 shadow-sm"><div className="grid gap-3 md:grid-cols-[1fr_auto_auto]"><label className="relative"><Search className="absolute left-3 top-3.5 size-4 text-slate-400"/><input className="min-h-11 w-full rounded-xl border pl-10 pr-3" placeholder="Search quizzes" value={query} onChange={e=>setQuery(e.target.value)}/></label><select className="rounded-xl border px-3" value={status} onChange={e=>setStatus(e.target.value)}><option value="active">Active</option><option value="all">All statuses</option><option value="draft">Drafts</option><option value="ready">Ready</option><option value="archived">Archived</option></select><select className="rounded-xl border px-3" value={subject} onChange={e=>setSubject(e.target.value)}><option value="all">All subjects</option><option value="mathematics">Mathematics</option><option value="english-language">English</option><option value="science">Science</option><option value="computing">Computing</option><option value="general">General</option></select></div></section>
 {busy&&!quizzes.length?<div className="grid place-items-center p-12"><Loader2 className="animate-spin"/></div>:<section className="grid gap-4 lg:grid-cols-2">{visible.map(q=><article className="rounded-[1.5rem] border bg-white p-5 shadow-sm" key={q.id}><div className="flex justify-between gap-3"><div><span className={`rounded-full px-2 py-1 text-xs font-black ${q.status==="ready"?"bg-emerald-100 text-emerald-800":"bg-amber-100 text-amber-800"}`}>{q.status}</span><h2 className="mt-3 text-xl font-black">{q.title}</h2><p className="mt-1 text-sm text-slate-500">{q.subject} · Basic {q.gradeLevels.join(", ")} · v{q.version}</p></div><ClipboardList className="size-8 text-violet-600"/></div><div className="mt-4 grid grid-cols-4 gap-2 text-center text-xs"><Stat n={q.questions.length} l="Questions"/><Stat n={q.assignmentCount} l="Classes"/><Stat n={q.averageScore??"—"} l="Avg %"/><Stat n={q.passRate??"—"} l="Pass %"/></div><div className="mt-4 flex flex-wrap gap-2"><button className="rounded-xl border px-3 py-2 text-sm font-bold" onClick={()=>setEditing(q)}>Edit</button><button className="rounded-xl border px-3 py-2 text-sm font-bold" onClick={()=>void mutate({...q,id:undefined,title:`${q.title} copy`,status:"draft"},"POST")}><Copy className="mr-1 inline size-4"/>Duplicate</button>{q.status==="ready"?<button className="rounded-xl bg-violet-600 px-3 py-2 text-sm font-bold text-white" onClick={()=>setAssigning(q)}><Send className="mr-1 inline size-4"/>Assign</button>:null}{q.status!=="archived"?<button className="rounded-xl px-3 py-2 text-sm font-bold text-rose-700" onClick={()=>void mutate({id:q.id,status:"archived"})}><Archive className="mr-1 inline size-4"/>Archive</button>:null}</div></article>)}</section>}
 {editing?<QuizEditorDialog quiz={editing} busy={busy} onClose={()=>setEditing(null)} onSave={(q)=>saveQuiz(q,q.id?"PATCH":"POST")}/>:null}
 {assigning?<AssignDialog quiz={assigning} classes={classes.filter(c=>c.status==="active")} onClose={()=>setAssigning(null)} onDone={()=>{setAssigning(null);void load()}}/>:null}</main>
}
function newQuiz():Quiz{return{id:"",title:"",description:"",subject:"mathematics",gradeLevels:[1],questions:[blankQuestion()],baseXpReward:40,passingScore:70,maxAttempts:3,version:1,status:"draft",assignmentCount:0,attemptCount:0,averageScore:null,passRate:null}}
function Stat({n,l}:{n:number|string;l:string}){return <div className="rounded-xl bg-slate-50 p-2"><b className="block text-lg">{n}</b><span>{l}</span></div>}
function AssignDialog({quiz,classes,onClose,onDone}:{quiz:Quiz;classes:TeacherClassSummary[];onClose:()=>void;onDone:()=>void}){
 const [ids,setIds]=useState<string[]>([]),[startAt,setStartAt]=useState(""),[deadline,setDeadline]=useState(""),[reward,setReward]=useState(""),[error,setError]=useState(""),[sending,setSending]=useState(false),[assigned,setAssigned]=useState(false);
 const online=useOnlineStatus();
 async function submit(){
  if(!online) return;
  setSending(true);setError("");
  try{
   const r=await fetch(`/api/teacher/quizzes/${quiz.id}/assignments`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({classIds:ids,startAt:startAt?new Date(startAt).toISOString():null,deadline:deadline?new Date(deadline).toISOString():null,offPlatformReward:reward})});
   const d=await r.json() as {error?:string;sms?:{sent:number;failed:number;skipped:number}};
   if(!r.ok)throw new Error(d.error||"Unable to assign quiz.");
   if(d.sms?.failed){setAssigned(true);setError(`Quiz assigned, but ${d.sms.failed} SMS message${d.sms.failed===1?"":"s"} could not be delivered.`);}
   else onDone();
  }catch(cause){setError(cause instanceof Error?cause.message:"Unable to assign quiz.")}
  finally{setSending(false)}
 }
 const invalidWindow=Boolean(startAt&&deadline&&new Date(startAt)>=new Date(deadline));
 return <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/70 p-3 sm:p-6"><div className="mx-auto w-full max-w-2xl overflow-hidden rounded-[1.75rem] bg-white shadow-2xl"><header className="flex items-start justify-between gap-4 bg-gradient-to-br from-slate-950 to-violet-900 p-5 text-white sm:p-6"><div><p className="text-xs font-black uppercase tracking-wider text-violet-300">Publish challenge</p><h2 className="mt-1 text-2xl font-black">Assign {quiz.title}</h2><p className="mt-2 text-sm text-violet-100">Learners receive an SMS with the schedule and a direct quiz link.</p></div><button aria-label="Close" className="grid size-10 shrink-0 place-items-center rounded-xl bg-white/10" onClick={onClose} type="button"><X/></button></header><div className="grid gap-5 p-5 sm:p-6">
  <fieldset><div className="flex items-center justify-between gap-3"><legend className="font-black">Choose classes</legend><span className="text-xs font-black text-violet-700">{ids.length} selected</span></div><div className="mt-3 grid gap-2 sm:grid-cols-2">{classes.map(c=><label className={`flex min-h-14 cursor-pointer items-center gap-3 rounded-xl border p-3 font-bold ${ids.includes(c.id)?"border-violet-500 bg-violet-50":"border-slate-200 bg-slate-50"}`} key={c.id}><input className="size-4 accent-violet-700" type="checkbox" checked={ids.includes(c.id)} onChange={()=>setIds(ids.includes(c.id)?ids.filter(x=>x!==c.id):[...ids,c.id])}/><span>{c.name}<small className="block font-semibold text-slate-500">Basic {c.gradeLevel} · {c.memberCount} learners</small></span></label>)}</div></fieldset>
  <section className="rounded-2xl border border-blue-200 bg-blue-50 p-4"><div className="flex gap-3"><CalendarClock className="size-5 shrink-0 text-blue-700"/><div><h3 className="font-black text-blue-950">Optional quiz schedule</h3><p className="mt-1 text-xs leading-5 text-blue-800">Leave both empty to open the quiz now until you close it. Add only an end time for a “take by” deadline.</p></div></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="grid gap-1.5 text-sm font-black">Starts at <input type="datetime-local" className="min-h-11 rounded-xl border border-blue-200 bg-white px-3" value={startAt} onChange={e=>setStartAt(e.target.value)}/></label><label className="grid gap-1.5 text-sm font-black">Ends / take by <input type="datetime-local" className="min-h-11 rounded-xl border border-blue-200 bg-white px-3" value={deadline} onChange={e=>setDeadline(e.target.value)}/></label></div>{invalidWindow?<p className="mt-2 text-xs font-bold text-rose-700">The end time must be after the start time.</p>:null}</section>
  <label className="rounded-2xl border border-amber-200 bg-amber-50 p-4"><span className="flex items-center gap-2 font-black text-amber-950"><Gift className="size-5 text-amber-700"/>Real-world reward (optional)</span><span className="mt-1 block text-xs leading-5 text-amber-800">Describe any classroom reward learners can earn, such as a standing clap, class privilege or no sweeping for a week.</span><textarea className="mt-3 min-h-24 w-full rounded-xl border border-amber-200 bg-white p-3" maxLength={500} placeholder="e.g. The highest score receives a standing clap and chooses Friday's class activity." value={reward} onChange={e=>setReward(e.target.value)}/><span className="mt-1 block text-right text-xs font-bold text-amber-700">{reward.length}/500</span></label>
  {error?<p className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm font-bold text-rose-800">{error}</p>:null}
  {assigned?<button className="inline-flex min-h-12 w-full items-center justify-center rounded-xl bg-slate-900 p-3 font-black text-white" onClick={onDone} type="button">Close and refresh quizzes</button>:<button disabled={!ids.length||invalidWindow||sending||!online} className="inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-violet-700 p-3 font-black text-white shadow-lg disabled:opacity-50" onClick={()=>void submit()}>{sending?<Loader2 className="size-4 animate-spin"/>:<Send className="size-4"/>}{sending?"Publishing and sending SMS…":`Assign and notify ${ids.length} class${ids.length===1?"":"es"}`}</button>}
 </div></div></div>
}
