"use client";
import { FormEvent, useEffect, useState } from "react";
import { ExternalLink, FileUp, FolderOpen, Loader2, ShieldCheck, Trash2, Upload } from "lucide-react";

type UploadItem={id:string;title:string;subject:string;gradeLevels:string[];authority:string;sourceUrl:string|null;publishedYear:number|null;fileName:string;fileSize:number;createdAt:string;downloadUrl:string|null};
const grades=["KG1","KG2","B1","B2","B3","B4","B5","B6"];
export function TeacherCurriculumUploads(){
 const[uploads,setUploads]=useState<UploadItem[]>([]),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const load=async()=>{const r=await fetch("/api/teacher/curriculum-uploads",{cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b.error);setUploads(b.uploads??[])};
 useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const form=new FormData(event.currentTarget);form.set("grades",form.getAll("grade").join(","));try{const r=await fetch("/api/teacher/curriculum-uploads",{method:"POST",body:form});const b=await r.json();if(!r.ok)throw new Error(b.error);event.currentTarget.reset();setOpen(false);await load()}catch(e){setError(e instanceof Error?e.message:"Upload failed.")}finally{setBusy(false)}}
 async function remove(id:string){if(!confirm("Delete this uploaded curriculum reference?"))return;const r=await fetch("/api/teacher/curriculum-uploads",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id})});const b=await r.json();if(!r.ok)setError(b.error);else load()}
 return <section className="overflow-hidden rounded-[2rem] bg-gradient-to-br from-slate-950 via-violet-950 to-indigo-800 text-white shadow-xl"><div className="p-6 sm:p-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><span className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1.5 text-[11px] font-black uppercase tracking-wider text-violet-200"><ShieldCheck className="size-4"/>Curriculum reference centre</span><h1 className="mt-4 text-3xl font-black sm:text-4xl">NaCCA Curriculum</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-violet-100/80 sm:text-base">Browse authoritative Ghana curriculum sources and keep your own school-approved curriculum files in a private teacher collection.</p></div><button className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-white px-5 font-black text-slate-950 hover:bg-violet-50" onClick={()=>setOpen(v=>!v)}><Upload className="size-5"/>{open?"Close upload form":"Upload curriculum"}</button></div></div>
 {open?<form className="grid gap-4 border-t border-white/10 bg-white/10 p-5 sm:p-6 lg:grid-cols-2" onSubmit={submit}><Field label="Curriculum title"><input name="title" required minLength={2} placeholder="e.g. School Computing Curriculum"/></Field><Field label="Subject"><input name="subject" required placeholder="e.g. Computing"/></Field><Field label="Authority or publisher"><input name="authority" placeholder="e.g. NaCCA or school curriculum office"/></Field><Field label="Published year"><input name="publishedYear" type="number" min={1900} max={2100}/></Field><Field label="Official source URL (optional)"><input name="sourceUrl" type="url" placeholder="https://…"/></Field><Field label="Curriculum file"><input name="file" required type="file" accept=".pdf,.doc,.docx,application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document"/></Field><fieldset className="lg:col-span-2"><legend className="text-sm font-black">Grades covered</legend><div className="mt-2 flex flex-wrap gap-2">{grades.map(g=><label className="cursor-pointer rounded-xl bg-white/10 px-3 py-2 text-sm font-black has-[:checked]:bg-white has-[:checked]:text-violet-900" key={g}><input className="sr-only" name="grade" type="checkbox" value={g}/>{g}</label>)}</div></fieldset><p className="text-xs text-violet-100 lg:col-span-2">PDF, DOC or DOCX · maximum 15 MB. Teacher uploads are labelled separately and are not presented as verified NaCCA records.</p><button className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-violet-500 px-4 font-black disabled:opacity-50 lg:col-span-2" disabled={busy}>{busy?<Loader2 className="size-5 animate-spin"/>:<FileUp className="size-5"/>}{busy?"Uploading…":"Save curriculum file"}</button></form>:null}
 {error?<p className="m-4 rounded-xl bg-rose-100 p-3 font-bold text-rose-900">{error}</p>:null}
 <div className="border-t border-white/10 bg-white p-5 text-slate-950 sm:p-6"><div className="flex items-end justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-wider text-violet-700">My uploads</p><h2 className="mt-1 text-xl font-black">Teacher curriculum files</h2></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-black">{uploads.length}</span></div>{uploads.length?<div className="mt-4 grid gap-3 lg:grid-cols-2">{uploads.map(item=><article className="rounded-2xl border border-slate-200 p-4" key={item.id}><div className="flex items-start gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-violet-100 text-violet-700"><FolderOpen className="size-5"/></span><div className="min-w-0 flex-1"><h3 className="truncate font-black">{item.title}</h3><p className="mt-1 text-xs font-bold text-slate-500">{item.subject} · {item.gradeLevels.join(" · ")}</p><p className="mt-2 text-xs text-slate-500">{item.authority||"Authority not specified"}{item.publishedYear?` · ${item.publishedYear}`:""} · {(item.fileSize/1048576).toFixed(1)} MB</p></div></div><div className="mt-3 flex gap-2">{item.downloadUrl?<a className="inline-flex min-h-10 items-center gap-2 rounded-xl bg-violet-50 px-3 text-xs font-black text-violet-800" href={item.downloadUrl} target="_blank" rel="noreferrer">Open file<ExternalLink className="size-3.5"/></a>:null}<button className="grid size-10 place-items-center rounded-xl text-rose-700 hover:bg-rose-50" aria-label={`Delete ${item.title}`} onClick={()=>remove(item.id)}><Trash2 className="size-4"/></button></div></article>)}</div>:<div className="mt-4 rounded-2xl border-2 border-dashed border-slate-200 p-7 text-center"><FolderOpen className="mx-auto size-8 text-slate-300"/><p className="mt-2 font-black">No teacher uploads yet</p><p className="text-sm text-slate-500">Official records remain available in the library below.</p></div>}</div>
 </section>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="grid gap-2 text-sm font-black">{label}<span className="[&>input]:min-h-11 [&>input]:w-full [&>input]:rounded-xl [&>input]:border [&>input]:border-white/20 [&>input]:bg-white [&>input]:px-3 [&>input]:text-slate-950 [&>input]:outline-none">{children}</span></label>}
