import { NextResponse } from "next/server";
import { z } from "zod";
import { requireAdmin } from "@/lib/classes/classroom-server";
import { createAdminClient } from "@/lib/supabase/admin";

const bucket="teacher-tutorials";
const categories=["getting_started","classes","subjects_lessons","quizzes","messages_safety","progress_support"] as const;
async function ensureBucket(){const admin=createAdminClient();const{data}=await admin.storage.getBucket(bucket);if(!data)await admin.storage.createBucket(bucket,{public:false,fileSizeLimit:500*1024*1024,allowedMimeTypes:["video/mp4","video/webm"]})}
export async function GET(){try{await requireAdmin();const{data,error}=await createAdminClient().from("TeacherTutorialVideo").select("*").order("position").order("createdAt");if(error)throw new Error(error.message);return NextResponse.json({videos:data??[]})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Could not load tutorials."},{status:400})}}
export async function POST(request:Request){try{const adminUser=await requireAdmin(),admin=createAdminClient(),body=await request.json();
 if(body.action==="prepare"){const input=z.object({fileName:z.string().min(1).max(200),mimeType:z.enum(["video/mp4","video/webm"]),fileSize:z.number().int().min(1).max(500*1024*1024)}).parse(body);await ensureBucket();const ext=input.mimeType==="video/webm"?"webm":"mp4",path=`${adminUser.id}/${crypto.randomUUID()}.${ext}`;const{data,error}=await admin.storage.from(bucket).createSignedUploadUrl(path);if(error)throw new Error(error.message);return NextResponse.json({path,token:data.token})}
 const input=z.object({action:z.literal("confirm"),path:z.string().min(10),fileName:z.string().min(1).max(200),mimeType:z.enum(["video/mp4","video/webm"]),fileSize:z.number().int().min(1).max(500*1024*1024),title:z.string().trim().min(3).max(160),description:z.string().trim().max(1000),category:z.enum(categories),durationMinutes:z.number().int().min(1).max(240).nullable()}).parse(body);
 if(!input.path.startsWith(`${adminUser.id}/`))throw new Error("Invalid upload path.");const{data:list}=await admin.storage.from(bucket).list(adminUser.id,{search:input.path.split("/").pop()});if(!list?.length)throw new Error("Uploaded video was not found.");
 const{data:last}=await admin.from("TeacherTutorialVideo").select("position").order("position",{ascending:false}).limit(1).maybeSingle();const{data,error}=await admin.from("TeacherTutorialVideo").insert({title:input.title,description:input.description,category:input.category,storagePath:input.path,fileName:input.fileName,mimeType:input.mimeType,fileSize:input.fileSize,durationMinutes:input.durationMinutes,status:"draft",position:Number(last?.position??-1)+1,createdBy:adminUser.id}).select("*").single();if(error)throw new Error(error.message);return NextResponse.json({video:data},{status:201});
 }catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Upload could not be saved."},{status:400})}}
export async function PATCH(request:Request){try{await requireAdmin();const input=z.object({id:z.string().uuid(),status:z.enum(["draft","published"]).optional(),position:z.number().int().min(0).optional(),title:z.string().trim().min(3).max(160).optional(),description:z.string().trim().max(1000).optional(),category:z.enum(categories).optional()}).parse(await request.json());const{id,...changes}=input;const{data,error}=await createAdminClient().from("TeacherTutorialVideo").update({...changes,updatedAt:new Date().toISOString()}).eq("id",id).select("*").single();if(error)throw new Error(error.message);return NextResponse.json({video:data})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Tutorial could not be updated."},{status:400})}}
export async function DELETE(request:Request){try{await requireAdmin();const{id}=z.object({id:z.string().uuid()}).parse(await request.json()),admin=createAdminClient();const{data}=await admin.from("TeacherTutorialVideo").select("storagePath").eq("id",id).maybeSingle();if(!data)throw new Error("Tutorial not found.");await admin.storage.from(bucket).remove([String(data.storagePath)]);const{error}=await admin.from("TeacherTutorialVideo").delete().eq("id",id);if(error)throw new Error(error.message);return NextResponse.json({ok:true})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Tutorial could not be deleted."},{status:400})}}
