"use client";
import { FormEvent,useEffect,useState } from "react";
import { ArrowDown,ArrowUp,Eye,EyeOff,Film,Loader2,PlayCircle,Trash2,Upload } from "lucide-react";
import { createBrowserSupabaseClient } from "@/lib/supabase/browser";

type Video={id:string;title:string;description:string;category:string;fileName:string;fileSize:number;durationMinutes:number|null;status:"draft"|"published";position:number;createdAt:string};
const categories=[["getting_started","Getting started"],["classes","Classes"],["subjects_lessons","Subjects & lessons"],["quizzes","Quizzes"],["messages_safety","Messages & safety"],["progress_support","Progress & support"]];
export function AdminTutorialVideos(){const[videos,setVideos]=useState<Video[]>([]),[busy,setBusy]=useState(false),[progress,setProgress]=useState(""),[error,setError]=useState("");
 const load=async()=>{const r=await fetch("/api/admin/tutorial-videos",{cache:"no-store"}),b=await r.json();if(!r.ok)throw new Error(b.error);setVideos(b.videos??[])};
 useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const form=e.currentTarget,file=(new FormData(form).get("file"));if(!(file instanceof File)){setError("Choose a video.");setBusy(false);return}try{setProgress("Preparing secure upload…");let r=await fetch("/api/admin/tutorial-videos",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"prepare",fileName:file.name,mimeType:file.type,fileSize:file.size})}),b=await r.json();if(!r.ok)throw new Error(b.error);setProgress("Uploading directly to secure storage…");const{error:uploadError}=await createBrowserSupabaseClient().storage.from("teacher-tutorials").uploadToSignedUrl(b.path,b.token,file,{contentType:file.type});if(uploadError)throw uploadError;const values=new FormData(form);setProgress("Saving tutorial details…");r=await fetch("/api/admin/tutorial-videos",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"confirm",path:b.path,fileName:file.name,mimeType:file.type,fileSize:file.size,title:values.get("title"),description:values.get("description"),category:values.get("category"),durationMinutes:values.get("durationMinutes")?Number(values.get("durationMinutes")):null})});b=await r.json();if(!r.ok)throw new Error(b.error);form.reset();setProgress("");await load()}catch(e){setError(e instanceof Error?e.message:"Upload failed.");setProgress("")}finally{setBusy(false)}}
 async function update(id:string,changes:object){setBusy(true);const r=await fetch("/api/admin/tutorial-videos",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,...changes})}),b=await r.json();if(!r.ok)setError(b.error);else await load();setBusy(false)}
 async function remove(id:string){if(!confirm("Delete this tutorial video permanently?"))return;const r=await fetch("/api/admin/tutorial-videos",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id})}),b=await r.json();if(!r.ok)setError(b.error);else load()}
 return <main className="mx-auto grid max-w-7xl gap-6"><header className="rounded-[2rem] bg-gradient-to-br from-slate-950 via-violet-950 to-indigo-800 p-7 text-white shadow-xl"><span className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1.5 text-xs font-black uppercase tracking-wider"><Film className="size-4"/>Teacher learning</span><h1 className="mt-4 text-3xl font-black sm:text-4xl">Tutorial videos</h1><p className="mt-2 max-w-2xl text-violet-100">Upload and organise the video guides teachers see in their learning centre. New videos remain drafts until you publish them.</p></header>
 {error?<p className="rounded-xl bg-rose-50 p-3 font-bold text-rose-800">{error}</p>:null}
 <div className="grid gap-6 xl:grid-cols-[23rem_minmax(0,1fr)]"><form className="grid content-start gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm xl:sticky xl:top-20" onSubmit={submit}><div><p className="text-xs font-black uppercase tracking-wider text-violet-700">New tutorial</p><h2 className="mt-1 text-xl font-black">Upload a video</h2></div><Field label="Title"><input name="title" minLength={3} required/></Field><Field label="Description"><textarea name="description" rows={4}/></Field><Field label="Category"><select name="category">{categories.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></Field><Field label="Duration in minutes"><input name="durationMinutes" type="number" min={1} max={240}/></Field><Field label="Video file"><input name="file" type="file" accept="video/mp4,video/webm,.mp4,.webm" required/></Field><p className="text-xs leading-5 text-slate-500">MP4 or WebM · up to 500 MB. The video uploads directly to private storage.</p><button className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-violet-700 px-4 font-black text-white disabled:opacity-50" disabled={busy}>{busy?<Loader2 className="size-5 animate-spin"/>:<Upload className="size-5"/>}{progress||"Upload as draft"}</button></form>
 <section><div className="flex items-end justify-between gap-3"><div><h2 className="text-2xl font-black">Video library</h2><p className="text-sm text-slate-500">Publish only videos that are ready for teachers.</p></div><span className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-black">{videos.length} videos</span></div><div className="mt-4 grid gap-3">{videos.map((v,index)=><article className="flex flex-col gap-4 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:flex-row sm:items-center" key={v.id}><span className={`grid size-12 shrink-0 place-items-center rounded-2xl ${v.status==="published"?"bg-emerald-100 text-emerald-700":"bg-amber-100 text-amber-700"}`}><PlayCircle className="size-6"/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-black">{v.title}</h3><span className={`rounded-full px-2 py-0.5 text-[10px] font-black uppercase ${v.status==="published"?"bg-emerald-100 text-emerald-800":"bg-amber-100 text-amber-800"}`}>{v.status}</span></div><p className="mt-1 line-clamp-2 text-sm text-slate-600">{v.description||"No description."}</p><p className="mt-2 text-xs font-bold text-slate-400">{categories.find(c=>c[0]===v.category)?.[1]} · {v.durationMinutes?`${v.durationMinutes} min · `:""}{(v.fileSize/1048576).toFixed(1)} MB</p></div><div className="flex shrink-0 gap-1"><button aria-label="Move video up" disabled={busy||index===0} className="grid size-10 place-items-center rounded-xl hover:bg-slate-100 disabled:opacity-30" onClick={()=>update(v.id,{position:Math.max(0,v.position-1)})}><ArrowUp className="size-4"/></button><button aria-label="Move video down" disabled={busy||index===videos.length-1} className="grid size-10 place-items-center rounded-xl hover:bg-slate-100 disabled:opacity-30" onClick={()=>update(v.id,{position:v.position+1})}><ArrowDown className="size-4"/></button><button aria-label={v.status==="published"?"Unpublish video":"Publish video"} className={`grid size-10 place-items-center rounded-xl ${v.status==="published"?"bg-amber-50 text-amber-700":"bg-emerald-50 text-emerald-700"}`} onClick={()=>update(v.id,{status:v.status==="published"?"draft":"published"})}>{v.status==="published"?<EyeOff className="size-4"/>:<Eye className="size-4"/>}</button><button aria-label="Delete video" className="grid size-10 place-items-center rounded-xl text-rose-700 hover:bg-rose-50" onClick={()=>remove(v.id)}><Trash2 className="size-4"/></button></div></article>)}{!videos.length?<div className="grid min-h-56 place-items-center rounded-2xl border-2 border-dashed border-slate-200 text-center"><div><Film className="mx-auto size-9 text-slate-300"/><p className="mt-3 font-black">No tutorial videos yet</p><p className="text-sm text-slate-500">Upload the first video using the form.</p></div></div>:null}</div></section></div></main>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="grid gap-2 text-sm font-black text-slate-700">{label}<span className="[&>input]:min-h-11 [&>input]:w-full [&>input]:rounded-xl [&>input]:border [&>input]:border-slate-300 [&>input]:px-3 [&>select]:min-h-11 [&>select]:w-full [&>select]:rounded-xl [&>select]:border [&>select]:border-slate-300 [&>select]:px-3 [&>textarea]:w-full [&>textarea]:rounded-xl [&>textarea]:border [&>textarea]:border-slate-300 [&>textarea]:p-3">{children}</span></label>}
