"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { ExternalLink, FileText, Search, Sparkles } from "lucide-react";
import { Input, Select } from "@/components/design-system/form-controls";
import { SkulKidCard } from "@/components/shared/skulkid-card";
import { ghanaPrimaryCurriculum, officialCurriculumSubjects } from "@/data/ghana-primary-curriculum";

export function OfficialCurriculumLibrary() {
  const [query, setQuery] = useState("");
  const [subject, setSubject] = useState("all");
  const [grade, setGrade] = useState("all");
  const documents = useMemo(() => ghanaPrimaryCurriculum.filter((document) => `${document.title} ${document.subject} ${document.note}`.toLowerCase().includes(query.toLowerCase()) && (subject === "all" || document.subject === subject) && (grade === "all" || document.gradeLevels.includes(grade))), [query, subject, grade]);

  return <section className="mt-10" aria-labelledby="official-library-heading">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-black uppercase tracking-wide text-violet-700">Official source library</p><h2 id="official-library-heading" className="mt-1 text-3xl font-black">Ghana standards-based curricula</h2><p className="mt-2 max-w-3xl leading-7 text-text-secondary">NaCCA, Ministry of Education and GES curriculum records for KG through Basic 6. Links open the authoritative NaCCA source; SkulKid stores the catalogue and provenance, not modified copies.</p></div><span className="shrink-0 rounded-full bg-violet-100 px-4 py-2 text-sm font-black text-violet-900">{ghanaPrimaryCurriculum.length} official documents</span></div>
    <SkulKidCard className="mt-5 p-4"><div className="grid gap-3 md:grid-cols-[1fr_15rem_10rem]"><label className="relative"><span className="sr-only">Search official curricula</span><Search className="pointer-events-none absolute left-4 top-3.5 size-4 text-muted" aria-hidden="true" /><Input className="pl-11" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search curricula" /></label><label><span className="sr-only">Filter by subject</span><Select value={subject} onChange={(event) => setSubject(event.target.value)}><option value="all">All subjects</option>{officialCurriculumSubjects.map((name) => <option key={name}>{name}</option>)}</Select></label><label><span className="sr-only">Filter by grade</span><Select value={grade} onChange={(event) => setGrade(event.target.value)}><option value="all">All grades</option>{["KG1", "KG2", "B1", "B2", "B3", "B4", "B5", "B6"].map((name) => <option key={name}>{name}</option>)}</Select></label></div></SkulKidCard>
    <div className="mt-5 grid gap-4 lg:grid-cols-2">{documents.map((document) => <SkulKidCard className="flex flex-col p-5" key={document.id}><div className="flex items-start gap-4"><span className="grid size-11 shrink-0 place-items-center rounded-2xl bg-violet-100 text-violet-700"><FileText className="size-5" aria-hidden="true" /></span><div className="min-w-0"><div className="flex flex-wrap gap-2"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold text-slate-700">{document.phase}</span><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${document.status === "current" ? "bg-green-100 text-green-900" : "bg-amber-100 text-amber-950"}`}>{document.status === "current" ? "Current library" : "Integrated from 2024/25"}</span></div><h3 className="mt-3 text-xl font-black">{document.title}</h3><p className="mt-1 text-sm font-bold text-violet-700">{document.gradeLevels.join(" · ")}</p></div></div><p className="mt-4 flex-1 text-sm leading-6 text-text-secondary">{document.note}</p><p className="mt-3 text-xs text-muted">Authority: {document.authority} · Published {document.year}</p><div className="mt-4 flex flex-wrap gap-2"><a href={document.documentUrl ?? document.officialSourceUrl} target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-slate-300 bg-white px-4 text-sm font-bold hover:bg-slate-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary">Open official {document.documentUrl ? "PDF" : "source"}<ExternalLink className="size-4" aria-hidden="true" /></a><Link href="/admin/curriculum-studio" className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-violet-50 px-4 text-sm font-bold text-violet-800 hover:bg-violet-100 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-violet-600"><Sparkles className="size-4" aria-hidden="true" />Create course</Link></div></SkulKidCard>)}</div>
    {documents.length === 0 ? <div className="mt-5 rounded-2xl border border-slate-200 bg-white p-8 text-center"><p className="font-bold">No curriculum documents match those filters.</p><button className="mt-3 text-sm font-bold text-violet-700" type="button" onClick={() => { setQuery(""); setSubject("all"); setGrade("all"); }}>Clear filters</button></div> : null}
  </section>;
}
