"use client";

import { useEffect, useState } from "react";
import { Loader2, ShieldAlert } from "lucide-react";

type SafetyCase = { id: string; source: string; categories: string[]; severity: string; summary: string; status: string; createdAt: string; acknowledgedAt: string | null; resolvedAt: string | null; resolutionNote: string | null };
export default function ChildSafetyPage() {
  const [cases, setCases] = useState<SafetyCase[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  async function load() { const response = await fetch("/api/admin/child-safety", { cache: "no-store" }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setCases(result.cases ?? []); }
  useEffect(() => { void load().catch((cause) => setError(cause.message)).finally(() => setLoading(false)); }, []);
  async function update(item: SafetyCase, status: "reviewing" | "resolved" | "dismissed") { const note = window.prompt(status === "reviewing" ? "Add an acknowledgement or investigation note:" : "Add the resolution and safeguarding actions taken:"); if (!note) return; const response = await fetch("/api/admin/child-safety", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ caseId: item.id, status, resolutionNote: note }) }); const result = await response.json(); if (!response.ok) setError(result.error); else await load(); }
  return <main className="mx-auto grid w-full max-w-7xl gap-5"><header><p className="text-xs font-black uppercase tracking-widest text-rose-700">Safeguarding</p><h1 className="mt-1 text-3xl font-black">Child-safety escalations</h1><p className="mt-2 text-slate-600">Acknowledge, investigate and resolve automatic detections and learner reports.</p></header>{error ? <p className="rounded-xl bg-rose-50 p-3 font-bold text-rose-800">{error}</p> : null}{loading ? <Loader2 className="size-8 animate-spin" /> : <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="grid grid-cols-3 gap-3 border-b bg-slate-50 p-4 text-center"><Stat label="Open" value={cases.filter((item) => item.status === "open").length} /><Stat label="Reviewing" value={cases.filter((item) => item.status === "reviewing").length} /><Stat label="Resolved" value={cases.filter((item) => item.status === "resolved").length} /></div><div className="divide-y">{cases.length ? cases.map((item) => <article className="p-5" key={item.id}><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-xs font-black uppercase ${["high", "critical"].includes(item.severity) ? "bg-rose-100 text-rose-900" : "bg-amber-100 text-amber-900"}`}>{item.severity}</span><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-black uppercase">{item.status}</span><span className="text-xs font-bold text-slate-500">{item.source.replaceAll("_", " ")}</span></div><h2 className="mt-3 font-black">{item.summary}</h2><p className="mt-1 text-sm capitalize text-slate-600">Signals: {item.categories.join(", ").replaceAll("_", " ") || "unspecified"}</p><p className="mt-2 text-xs text-slate-500">Detected {new Date(item.createdAt).toLocaleString()}</p>{item.resolutionNote ? <p className="mt-3 rounded-xl bg-slate-50 p-3 text-sm"><b>Case note:</b> {item.resolutionNote}</p> : null}<div className="mt-4 flex flex-wrap gap-2">{item.status === "open" ? <button className="rounded-xl bg-amber-500 px-3 py-2 text-sm font-black" onClick={() => void update(item, "reviewing")}>Acknowledge</button> : null}{!["resolved", "dismissed"].includes(item.status) ? <button className="rounded-xl bg-emerald-700 px-3 py-2 text-sm font-black text-white" onClick={() => void update(item, "resolved")}>Resolve case</button> : null}<button className="rounded-xl border border-slate-300 px-3 py-2 text-sm font-bold" onClick={() => void update(item, "dismissed")}>Dismiss</button></div></article>) : <div className="grid min-h-48 place-items-center text-center"><div><ShieldAlert className="mx-auto size-8 text-emerald-600" /><b className="mt-2 block">No safety cases</b></div></div>}</div></section>}</main>;
}
function Stat({ label, value }: { label: string; value: number }) { return <div><strong className="block text-2xl">{value}</strong><span className="text-xs font-black uppercase text-slate-500">{label}</span></div>; }
